// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webcore2.Data;

namespace webcore2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190523201529_DbCreate")]
    partial class DbCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("webcore2.Models.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("fullName");

                    b.Property<string>("phoneNumber");

                    b.HasKey("id");

                    b.ToTable("customers");
                });
#pragma warning restore 612, 618
        }
    }
}
